"""
Ground station packet decoder.

Packet structure is imported directly from the flight computer source at
  ../Altairfc_V2/altairfc/
so there is a single source of truth. No packet definitions live here.

If the flight computer source is not found at the relative path, a
FileNotFoundError is raised at startup with a clear message.

Wire format (defined in altairfc/telemetry/serializer.py):
  [SYNC:1][PKT_ID:1][SEQ:1][TIMESTAMP:8 float64 LE][LEN:2 uint16 LE][DATA:N][CRC16:2 LE]
"""
from __future__ import annotations

import binascii
import dataclasses
import importlib
import struct
import sys
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Bootstrap: add altairfc/ to sys.path so its packages are importable
# ---------------------------------------------------------------------------

_FC_ROOT = (Path(__file__).parent.parent.parent / "Altairfc_V2" / "altairfc").resolve()

if not _FC_ROOT.exists():
    raise FileNotFoundError(
        f"Flight computer source not found at {_FC_ROOT}.\n"
        "Ensure Altairfc_V2 is checked out next to ALTAIR_GS_V3."
    )

if str(_FC_ROOT) not in sys.path:
    sys.path.insert(0, str(_FC_ROOT))

# Import the registry singleton and all packet modules so their
# @register decorators fire and populate the registry.
from telemetry.registry import packet_registry, FieldMeta  # noqa: E402

# Auto-discover every *.py module under telemetry/packets/ (excluding __init__)
_PACKETS_DIR = _FC_ROOT / "telemetry" / "packets"
for _p in sorted(_PACKETS_DIR.glob("*.py")):
    if _p.stem != "__init__":
        importlib.import_module(f"telemetry.packets.{_p.stem}")

# ---------------------------------------------------------------------------
# Build the decoder registry from the flight computer's packet_registry.
# Each entry needs: LABEL, STRUCT_FMT, FIELDS (for the frontend display).
# These are derived from the dataclass and its FieldMeta metadata.
# ---------------------------------------------------------------------------

def _label_from_classname(name: str) -> str:
    """'AttitudePacket' -> 'Attitude'"""
    return name.removesuffix("Packet")


def _build_fields(cls: type) -> list[dict]:
    """
    Extract display metadata from each dataclass field's FieldMeta.
    Returns a list of {"name", "label", "unit"} dicts in field order.
    """
    result = []
    for f in dataclasses.fields(cls):
        meta: FieldMeta = f.metadata.get("field_meta")
        if meta is None:
            continue
        result.append({
            "name":  f.name,
            "label": meta.description,
            "unit":  meta.units,
        })
    return result


# REGISTRY maps packet_id -> {"cls", "struct", "label", "fields"}
# AckPacket (0xA0) is excluded: it is a FC→GS control packet handled
# separately in _broadcast and must not appear as a telemetry panel or
# be generated by the emulator.
_EXCLUDED_PACKET_NAMES = {"AckPacket"}

REGISTRY: dict[int, dict] = {}

for _pid, _cls in packet_registry.all_packets().items():
    if _cls.__name__ in _EXCLUDED_PACKET_NAMES:
        continue
    _, _pkt_struct = packet_registry.get_by_id(_pid)
    REGISTRY[_pid] = {
        "cls":    _cls,
        "struct": _pkt_struct,
        "label":  getattr(_cls, "LABEL", _label_from_classname(_cls.__name__)),
        "fields": _build_fields(_cls),
    }

# ---------------------------------------------------------------------------
# Wire format constants (must match altairfc/telemetry/serializer.py)
# ---------------------------------------------------------------------------

SYNC_BYTE   = 0xAA
_HEADER     = struct.Struct("<BBBdH")   # sync, pkt_id, seq, timestamp, length
_CRC        = struct.Struct("<H")
HEADER_SIZE = _HEADER.size              # 13
CRC_SIZE    = _CRC.size                 # 2
MIN_FRAME   = HEADER_SIZE + CRC_SIZE    # 15

# ---------------------------------------------------------------------------
# Decoder
# ---------------------------------------------------------------------------

def decode_frame(raw: bytes) -> dict[str, Any] | None:
    """
    Decode one complete frame. Returns a JSON-serialisable dict on success,
    None on any validation failure.

    Returned dict shape:
    {
      "packet_id": 1,
      "label":     "Attitude",
      "seq":       42,
      "timestamp": 12.345,
      "fields": [
        {"name": "roll", "label": "Roll angle", "unit": "rad", "value": -0.012},
        ...
      ]
    }
    """
    if len(raw) < MIN_FRAME:
        return None

    sync, pkt_id, seq, timestamp, length = _HEADER.unpack_from(raw, 0)

    if sync != SYNC_BYTE:
        return None
    if len(raw) < HEADER_SIZE + length + CRC_SIZE:
        return None

    received_crc = _CRC.unpack_from(raw, HEADER_SIZE + length)[0]
    computed_crc = binascii.crc_hqx(raw[1: HEADER_SIZE + length], 0xFFFF)
    if received_crc != computed_crc:
        return None

    entry = REGISTRY.get(pkt_id)
    if entry is None:
        return None

    payload = raw[HEADER_SIZE: HEADER_SIZE + length]
    if len(payload) != entry["struct"].size:
        return None

    values = entry["struct"].unpack(payload)

    return {
        "packet_id": pkt_id,
        "label":     entry["label"],
        "seq":       seq,
        "timestamp": round(timestamp, 4),
        "fields": [
            {**fd, "value": round(v, 6)}
            for fd, v in zip(entry["fields"], values)
        ],
    }
